"""Website-controlled evaluation workers for the registered CLI harnesses."""

import asyncio
import json
import logging
import os
import shutil
import signal
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import httpx
from pydantic import BaseModel, ConfigDict, Field, model_validator

from .config import EvaluatorRuntimeSettings
from .muse import (
    fetch_muse_catalog,
    muse_command,
    muse_credential,
    muse_environment,
    muse_result,
    write_muse_config,
)

logger = logging.getLogger(__name__)


class ProposalPosition(BaseModel):
    model_config = ConfigDict(extra="forbid")

    symbol: str = Field(min_length=1, max_length=32)
    weight_pct: float = Field(gt=0, le=100)
    note: str = Field(max_length=2000)


class Proposal(BaseModel):
    model_config = ConfigDict(extra="forbid")

    status: Literal["proposal", "blocked"]
    positions: list[ProposalPosition]
    note: str = Field(max_length=4000)
    report: str = Field(max_length=20_000)
    error: str = Field(max_length=4000)

    @model_validator(mode="after")
    def validate_status_payload(self):
        if self.status == "proposal":
            if not self.positions:
                raise ValueError("A proposal must contain at least one position")
            if self.error:
                raise ValueError("A proposal cannot contain an error")
        else:
            if self.positions:
                raise ValueError("A blocked result cannot contain positions")
            if not self.error.strip():
                raise ValueError("A blocked result must explain the error")
        return self


class PortfolioRef(BaseModel):
    id: int
    slug: str
    name: str


class ClaimedRun(BaseModel):
    id: int
    portfolio: PortfolioRef
    trigger_kind: Literal["scheduled", "manual", "retry"]
    harness: Literal["codex", "muse"]
    execution_model_id: str
    reasoning_effort: str | None
    timeout_seconds: int
    execution_prompt: str = Field(min_length=1)


class ClaimSettings(BaseModel):
    enabled: bool
    poll_seconds: int


class ClaimResponse(BaseModel):
    settings: ClaimSettings
    runs: list[ClaimedRun]


class RunCancelled(RuntimeError):
    """The administrator cancelled an active process."""


class EvaluationBlocked(RuntimeError):
    """The harness could not produce a valid portfolio proposal."""


@dataclass
class WorkerState:
    status: str = "starting"
    harness_version: str | None = None
    authenticated: bool = False
    active_run_count: int = 0
    last_error: str | None = None
    poll_seconds: int = 60


def _toml_string(value: str) -> str:
    return json.dumps(value)


def write_codex_config(settings: EvaluatorRuntimeSettings) -> None:
    settings.codex_home.mkdir(parents=True, exist_ok=True)
    config = f"""\
# Generated by Portfolio Arena. Authentication files in this directory are
# preserved; only the dedicated evaluator configuration is replaced.
web_search = "live"
approval_policy = "never"
default_permissions = ":read-only"

[mcp_servers.portfolio_arena]
url = {_toml_string(settings.internal_mcp_url)}
bearer_token_env_var = "ARENA_INTERNAL_MCP_API_KEY"
enabled_tools = ["get_portfolio", "get_effective_date", "validate_symbol", "search_symbols"]
default_tools_approval_mode = "approve"
required = true

[mcp_servers.massive]
command = "/bin/bash"
args = ["-lc", "exec mcp_massive"]
env_vars = ["MASSIVE_API_KEY"]
default_tools_approval_mode = "approve"
required = true
"""
    (settings.codex_home / "config.toml").write_text(config)


def codex_environment(settings: EvaluatorRuntimeSettings) -> dict[str, str]:
    environment = os.environ.copy()
    environment["CODEX_HOME"] = str(settings.codex_home)
    environment["ARENA_INTERNAL_MCP_API_KEY"] = settings.internal_token
    environment["MASSIVE_API_KEY"] = settings.massive_api_key
    environment.pop("OPENAI_API_KEY", None)
    environment.pop("CODEX_API_KEY", None)
    environment.pop("META_API_KEY", None)
    return environment


async def internal_request(
    settings: EvaluatorRuntimeSettings,
    method: str,
    path: str,
    payload: dict | None = None,
) -> dict:
    if not settings.internal_token:
        raise RuntimeError("ARENA_INTERNAL_MCP_API_KEY is unavailable")
    timeout = httpx.Timeout(30, read=60)
    async with httpx.AsyncClient(
        base_url=settings.internal_api_url,
        headers={"Authorization": f"Bearer {settings.internal_token}"},
        timeout=timeout,
    ) as client:
        response = await client.request(method, path, json=payload)
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict):
            raise RuntimeError("Internal evaluator API returned a non-object response")
        return result


async def codex_version() -> str:
    executable = shutil.which("codex")
    if executable is None:
        raise RuntimeError("codex executable is not installed")
    process = await asyncio.create_subprocess_exec(
        executable,
        "--version",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await process.communicate()
    if process.returncode != 0:
        raise RuntimeError((stderr or stdout).decode(errors="replace").strip())
    return stdout.decode().strip()


async def muse_version(settings: EvaluatorRuntimeSettings) -> str:
    executable = shutil.which("muse")
    if executable is None:
        raise RuntimeError("muse executable is not installed")
    process = await asyncio.create_subprocess_exec(
        executable,
        "--version",
        stdin=asyncio.subprocess.DEVNULL,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
        env=muse_environment(settings),
        start_new_session=True,
    )
    try:
        stdout, stderr = await asyncio.wait_for(process.communicate(), timeout=30)
    except TimeoutError:
        raise RuntimeError("Muse version check timed out") from None
    finally:
        await _stop_process(process)
    if process.returncode != 0:
        raise RuntimeError(stderr.decode(errors="replace")[-4000:] or "Muse version check failed")
    return stdout.decode().strip()


async def codex_is_authenticated(settings: EvaluatorRuntimeSettings) -> bool:
    executable = shutil.which("codex")
    if executable is None:
        return False
    process = await asyncio.create_subprocess_exec(
        executable,
        "login",
        "status",
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL,
        env=codex_environment(settings),
    )
    return await process.wait() == 0


def evaluator_prompt(run: ClaimedRun) -> str:
    return run.execution_prompt


async def _wait_for_cancellation(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
) -> str:
    while True:
        await asyncio.sleep(2)
        try:
            control = await internal_request(settings, "GET", f"/runs/{run.id}/control")
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code == 404:
                return "Portfolio or evaluation run was deleted."
            logger.exception("evaluation_control_poll_failed run_id=%s", run.id)
            continue
        except Exception:
            logger.exception("evaluation_control_poll_failed run_id=%s", run.id)
            continue
        if control.get("status") in {"cancel_requested", "cancelled"}:
            return "Cancelled by an administrator."


async def _stop_process(process: asyncio.subprocess.Process) -> None:
    # Each evaluation owns a process group, including its MCP children.
    # Clean the group even if the harness parent has already exited.
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        return
    try:
        await asyncio.wait_for(process.wait(), timeout=5)
    except TimeoutError:
        pass
    finally:
        # The parent can exit while an MCP child ignores SIGTERM or holds the
        # output pipes open. Always finish cleanup of the entire group.
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        await process.wait()


async def _communicate_run(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
    process: asyncio.subprocess.Process,
    prompt: bytes | None,
) -> tuple[bytes, bytes]:
    communicate_task = asyncio.create_task(process.communicate(prompt))
    cancellation_task = asyncio.create_task(_wait_for_cancellation(settings, run))
    try:
        done, _ = await asyncio.wait(
            {communicate_task, cancellation_task},
            timeout=run.timeout_seconds,
            return_when=asyncio.FIRST_COMPLETED,
        )
        if cancellation_task in done:
            raise RunCancelled(cancellation_task.result())
        if communicate_task not in done:
            raise RuntimeError(f"{run.harness} attempt exceeded {run.timeout_seconds} seconds")
        return communicate_task.result()
    finally:
        cancellation_task.cancel()
        await _stop_process(process)
        await asyncio.gather(communicate_task, cancellation_task, return_exceptions=True)


async def run_codex(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
) -> Proposal:
    schema_path = Path(__file__).with_name("proposal.schema.json")
    with tempfile.TemporaryDirectory(prefix="arena-evaluation-") as temp_dir:
        output_path = Path(temp_dir) / "proposal.json"
        command = [
            "codex",
            "exec",
            "--strict-config",
            "--ephemeral",
            "--skip-git-repo-check",
            "--ignore-rules",
            "--sandbox",
            "read-only",
            "--model",
            run.execution_model_id,
        ]
        if run.reasoning_effort is not None:
            command.extend(["--config", f'model_reasoning_effort="{run.reasoning_effort}"'])
        command.extend(
            [
                "--cd",
                temp_dir,
                "--output-schema",
                str(schema_path),
                "--output-last-message",
                str(output_path),
                "--color",
                "never",
                "-",
            ]
        )
        process = await asyncio.create_subprocess_exec(
            *command,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=codex_environment(settings),
            start_new_session=True,
        )
        stdout, stderr = await _communicate_run(settings, run, process, evaluator_prompt(run).encode())
        if process.returncode != 0:
            detail = (stderr or stdout).decode(errors="replace").strip()
            raise RuntimeError(detail[-4000:] or f"Codex exited with {process.returncode}")
        if not output_path.exists():
            raise RuntimeError("Codex completed without writing a proposal")
        return Proposal.model_validate_json(output_path.read_text())


async def run_muse(settings: EvaluatorRuntimeSettings, run: ClaimedRun) -> Proposal:
    schema = Path(__file__).with_name("proposal.schema.json").read_text()
    prompt = (
        f"{evaluator_prompt(run)}\n\n"
        "Return the final result as one JSON object, without commentary or Markdown fences. "
        "The worker validates this JSON against the following schema before submitting it.\n"
        f"{schema}"
    )
    with tempfile.TemporaryDirectory(prefix="arena-muse-evaluation-") as temp_dir:
        workspace = Path(temp_dir)
        prompt_path = workspace / "prompt.txt"
        prompt_path.write_text(prompt)
        process = await asyncio.create_subprocess_exec(
            *muse_command(run.execution_model_id, run.reasoning_effort, workspace, prompt_path),
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=workspace,
            env=muse_environment(settings),
            start_new_session=True,
        )
        stdout, stderr = await _communicate_run(settings, run, process, None)
        if process.returncode != 0:
            # Prefer the structured terminal reason when Muse produced one.
            try:
                muse_result(stdout)
            except ValueError as exc:
                detail = f"{exc}\n{stderr.decode(errors='replace')}".strip()
                raise RuntimeError(detail[-4000:]) from exc
            detail = stderr.decode(errors="replace")[-4000:] or f"Muse exited with {process.returncode}"
            raise RuntimeError(detail)
        return Proposal.model_validate_json(muse_result(stdout))


async def evaluate_run(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
) -> None:
    try:
        proposal = await (run_muse(settings, run) if run.harness == "muse" else run_codex(settings, run))
        if proposal.status == "blocked":
            raise EvaluationBlocked(proposal.error)
        await internal_request(
            settings,
            "POST",
            f"/runs/{run.id}/submit",
            {
                "positions": [position.model_dump() for position in proposal.positions],
                "note": proposal.note,
                "report": proposal.report,
            },
        )
        logger.info("evaluation_succeeded portfolio=%s run_id=%s", run.portfolio.slug, run.id)
    except RunCancelled as exc:
        logger.info("evaluation_cancelled portfolio=%s run_id=%s", run.portfolio.slug, run.id)
        try:
            await internal_request(
                settings,
                "POST",
                f"/runs/{run.id}/fail",
                {"error": str(exc), "cancelled": True},
            )
        except httpx.HTTPStatusError as failure:
            if failure.response.status_code != 404:
                raise
    except Exception as exc:
        message = f"{type(exc).__name__}: {exc}"
        logger.error(
            "evaluation_failed portfolio=%s run_id=%s error=%s",
            run.portfolio.slug,
            run.id,
            message,
        )
        try:
            await internal_request(
                settings,
                "POST",
                f"/runs/{run.id}/fail",
                {"error": message[-4000:], "cancelled": False},
            )
        except Exception:
            logger.exception("evaluation_failure_record_failed run_id=%s", run.id)


async def scheduler(
    settings: EvaluatorRuntimeSettings,
    instance_id: str,
    state: WorkerState,
    harness: Literal["codex", "muse"],
) -> None:
    active_tasks: set[asyncio.Task[None]] = set()
    catalog_imported = False
    try:
        while True:
            try:
                if harness == "muse":
                    write_muse_config(settings)
                else:
                    write_codex_config(settings)
                if not settings.massive_api_key:
                    state.status = "configuration_error"
                    state.authenticated = False
                    state.last_error = "MASSIVE_API_KEY is required."
                else:
                    if harness == "muse":
                        state.harness_version = await muse_version(settings)
                        state.authenticated = bool(muse_credential(settings))
                    else:
                        state.harness_version = await codex_version()
                        state.authenticated = await codex_is_authenticated(settings)
                    if not state.authenticated:
                        state.status = "authentication_required"
                        state.last_error = (
                            f"Run `XDG_CONFIG_HOME={settings.muse_config_home} muse login` "
                            "in the application terminal or configure META_API_KEY."
                            if harness == "muse"
                            else "Run `codex login --device-auth` in the application terminal."
                        )
                    else:
                        if harness == "muse" and not catalog_imported:
                            catalog = await fetch_muse_catalog(settings)
                            await internal_request(settings, "POST", "/models/import-muse", catalog)
                            catalog_imported = True
                        response = ClaimResponse.model_validate(
                            await internal_request(
                                settings,
                                "POST",
                                "/claim",
                                {
                                    "worker_id": instance_id,
                                    "harness": harness,
                                    "harness_version": state.harness_version,
                                    "limit": 20,
                                },
                            )
                        )
                        state.poll_seconds = response.settings.poll_seconds
                        active_tasks.update(
                            asyncio.create_task(evaluate_run(settings, run)) for run in response.runs
                        )
                        state.active_run_count = len(active_tasks)
                        state.last_error = None
                        if not response.settings.enabled:
                            state.status = "paused"
                        elif active_tasks:
                            state.status = "running"
                        else:
                            state.status = "idle"
            except asyncio.CancelledError:
                raise
            except httpx.HTTPStatusError as exc:
                state.status = "error"
                state.last_error = f"HTTP {exc.response.status_code}: evaluator request failed."
                logger.exception("evaluator_request_failed harness=%s", harness)
            except Exception as exc:
                state.status = "error"
                state.last_error = f"{type(exc).__name__}: {exc}"[-4000:]
                logger.exception("evaluator_poll_failed")

            if active_tasks:
                completed, _ = await asyncio.wait(
                    active_tasks,
                    timeout=state.poll_seconds,
                    return_when=asyncio.FIRST_COMPLETED,
                )
                if completed:
                    await asyncio.gather(*completed, return_exceptions=True)
                    active_tasks.difference_update(completed)
                    state.active_run_count = len(active_tasks)
            else:
                await asyncio.sleep(state.poll_seconds)
    finally:
        for task in active_tasks:
            task.cancel()
        await asyncio.gather(*active_tasks, return_exceptions=True)


async def heartbeat_loop(
    settings: EvaluatorRuntimeSettings,
    instance_id: str,
    state: WorkerState,
    harness: Literal["codex", "muse"],
) -> None:
    while True:
        try:
            await internal_request(
                settings,
                "POST",
                "/heartbeat",
                {
                    "instance_id": instance_id,
                    "harness": harness,
                    "status": state.status,
                    "harness_version": state.harness_version,
                    "authenticated": state.authenticated,
                    "active_run_count": state.active_run_count,
                    "last_error": state.last_error,
                },
            )
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("evaluator_heartbeat_failed")
        await asyncio.sleep(min(state.poll_seconds, 60))


def worker_state_payload(state: WorkerState) -> dict[str, Any]:
    """Return a stable snapshot for focused unit tests."""
    return {
        "status": state.status,
        "harness_version": state.harness_version,
        "authenticated": state.authenticated,
        "active_run_count": state.active_run_count,
        "last_error": state.last_error,
        "poll_seconds": state.poll_seconds,
    }
