"""Website-controlled, ChatGPT-authenticated Codex evaluation worker."""

import asyncio
import json
import logging
import os
import shutil
import tempfile
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Literal

import httpx
from pydantic import BaseModel, Field

from .config import EvaluatorRuntimeSettings

logger = logging.getLogger(__name__)


class ProposalPosition(BaseModel):
    symbol: str = Field(min_length=1, max_length=32)
    weight_pct: float = Field(gt=0, le=100)
    note: str = Field(max_length=2000)


class Proposal(BaseModel):
    positions: list[ProposalPosition] = Field(min_length=1)
    note: str = Field(max_length=4000)
    report: str = Field(max_length=20_000)


class PortfolioRef(BaseModel):
    id: int
    slug: str
    name: str


class ClaimedRun(BaseModel):
    id: int
    portfolio: PortfolioRef
    trigger_kind: Literal["scheduled", "manual", "retry"]
    harness: Literal["codex"]
    execution_model_id: str
    reasoning_effort: str | None
    timeout_seconds: int
    deadline_at: datetime | None


class ClaimSettings(BaseModel):
    enabled: bool
    poll_seconds: int


class ClaimResponse(BaseModel):
    settings: ClaimSettings
    runs: list[ClaimedRun]


class RunCancelled(RuntimeError):
    """The administrator or scheduled cutoff cancelled an active process."""


@dataclass
class WorkerState:
    status: str = "starting"
    harness_version: str | None = None
    authenticated: bool = False
    active_run_count: int = 0
    last_error: str | None = None
    poll_seconds: int = 60


def _toml_string(value: str) -> str:
    return json.dumps(value)


def write_codex_config(settings: EvaluatorRuntimeSettings) -> None:
    settings.codex_home.mkdir(parents=True, exist_ok=True)
    config = f"""\
# Generated by Portfolio Arena. Authentication files in this directory are
# preserved; only the dedicated evaluator configuration is replaced.
web_search = "live"
approval_policy = "never"
default_permissions = ":read-only"

[mcp_servers.portfolio_arena]
url = {_toml_string(settings.internal_mcp_url)}
bearer_token_env_var = "ARENA_INTERNAL_MCP_API_KEY"
enabled_tools = ["get_portfolio", "get_effective_date", "validate_symbol", "search_symbols"]
required = true

[mcp_servers.massive]
command = "mcp_massive"
required = true
"""
    (settings.codex_home / "config.toml").write_text(config)


def codex_environment(settings: EvaluatorRuntimeSettings) -> dict[str, str]:
    environment = os.environ.copy()
    environment["CODEX_HOME"] = str(settings.codex_home)
    environment["ARENA_INTERNAL_MCP_API_KEY"] = settings.internal_token
    environment["MASSIVE_API_KEY"] = settings.massive_api_key
    environment.pop("OPENAI_API_KEY", None)
    environment.pop("CODEX_API_KEY", None)
    return environment


async def internal_request(
    settings: EvaluatorRuntimeSettings,
    method: str,
    path: str,
    payload: dict | None = None,
) -> dict:
    if not settings.internal_token:
        raise RuntimeError("ARENA_INTERNAL_MCP_API_KEY is unavailable")
    timeout = httpx.Timeout(30, read=60)
    async with httpx.AsyncClient(
        base_url=settings.internal_api_url,
        headers={"Authorization": f"Bearer {settings.internal_token}"},
        timeout=timeout,
    ) as client:
        response = await client.request(method, path, json=payload)
        response.raise_for_status()
        result = response.json()
        if not isinstance(result, dict):
            raise RuntimeError("Internal evaluator API returned a non-object response")
        return result


async def codex_version() -> str:
    executable = shutil.which("codex")
    if executable is None:
        raise RuntimeError("codex executable is not installed")
    process = await asyncio.create_subprocess_exec(
        executable,
        "--version",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await process.communicate()
    if process.returncode != 0:
        raise RuntimeError((stderr or stdout).decode(errors="replace").strip())
    return stdout.decode().strip()


async def codex_is_authenticated() -> bool:
    executable = shutil.which("codex")
    if executable is None:
        return False
    process = await asyncio.create_subprocess_exec(
        executable,
        "login",
        "status",
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL,
    )
    return await process.wait() == 0


def evaluator_prompt(run: ClaimedRun) -> str:
    return f"""\
Evaluate the existing Portfolio Arena portfolio `{run.portfolio.slug}` and produce its next allocation.

Call the Portfolio Arena `get_portfolio` tool first and treat the returned strategy, allocation
policy, holdings, notes, history, performance, and effective date as authoritative. Research all
decision-relevant current information with Massive and live web search. Every current holding must
re-earn its place, but continuity is useful when the thesis still holds.

Produce a proposal that obeys the returned allocation policy exactly. Use only USD-denominated
equities and ETFs accepted by Portfolio Arena. Do not use cash, mutual funds, options, futures,
indices, FX, shorts, or leverage. Validate unfamiliar symbols. Do not call any write tool: the
worker will validate and submit your final structured proposal atomically.

The report should briefly explain the portfolio-level decision, key evidence, material risks, and
what would change the next evaluation. Position notes should be concise handoff context.
"""


async def _wait_for_cancellation(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
) -> str:
    while True:
        await asyncio.sleep(2)
        if run.deadline_at is not None and datetime.now(UTC) >= run.deadline_at:
            return "Scheduled evaluation cutoff passed."
        try:
            control = await internal_request(settings, "GET", f"/runs/{run.id}/control")
        except Exception:
            logger.exception("evaluation_control_poll_failed run_id=%s", run.id)
            continue
        if control.get("status") in {"cancel_requested", "cancelled"}:
            return "Cancelled by an administrator."


async def _stop_process(process: asyncio.subprocess.Process) -> None:
    if process.returncode is not None:
        return
    process.terminate()
    try:
        await asyncio.wait_for(process.wait(), timeout=5)
    except TimeoutError:
        process.kill()
        await process.wait()


async def run_codex(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
) -> Proposal:
    schema_path = Path(__file__).with_name("proposal.schema.json")
    with tempfile.TemporaryDirectory(prefix="arena-evaluation-") as temp_dir:
        output_path = Path(temp_dir) / "proposal.json"
        command = [
            "codex",
            "exec",
            "--strict-config",
            "--ephemeral",
            "--skip-git-repo-check",
            "--ignore-rules",
            "--sandbox",
            "read-only",
            "--model",
            run.execution_model_id,
        ]
        if run.reasoning_effort is not None:
            command.extend(["--config", f'model_reasoning_effort="{run.reasoning_effort}"'])
        command.extend(
            [
                "--cd",
                temp_dir,
                "--output-schema",
                str(schema_path),
                "--output-last-message",
                str(output_path),
                "--color",
                "never",
                "-",
            ]
        )
        process = await asyncio.create_subprocess_exec(
            *command,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=codex_environment(settings),
        )
        communicate_task = asyncio.create_task(process.communicate(evaluator_prompt(run).encode()))
        cancellation_task = asyncio.create_task(_wait_for_cancellation(settings, run))
        try:
            done, _ = await asyncio.wait(
                {communicate_task, cancellation_task},
                timeout=run.timeout_seconds,
                return_when=asyncio.FIRST_COMPLETED,
            )
            if cancellation_task in done:
                reason = cancellation_task.result()
                await _stop_process(process)
                await communicate_task
                raise RunCancelled(reason)
            if communicate_task not in done:
                await _stop_process(process)
                await communicate_task
                raise RuntimeError(f"Codex attempt exceeded {run.timeout_seconds} seconds")
            stdout, stderr = communicate_task.result()
        finally:
            cancellation_task.cancel()
            await asyncio.gather(cancellation_task, return_exceptions=True)
        if process.returncode != 0:
            detail = (stderr or stdout).decode(errors="replace").strip()
            raise RuntimeError(detail[-4000:] or f"Codex exited with {process.returncode}")
        if not output_path.exists():
            raise RuntimeError("Codex completed without writing a proposal")
        return Proposal.model_validate_json(output_path.read_text())


async def evaluate_run(
    settings: EvaluatorRuntimeSettings,
    run: ClaimedRun,
) -> None:
    try:
        proposal = await run_codex(settings, run)
        await internal_request(
            settings,
            "POST",
            f"/runs/{run.id}/submit",
            {
                "positions": [position.model_dump() for position in proposal.positions],
                "note": proposal.note,
                "report": proposal.report,
            },
        )
        logger.info("evaluation_succeeded portfolio=%s run_id=%s", run.portfolio.slug, run.id)
    except RunCancelled as exc:
        logger.info("evaluation_cancelled portfolio=%s run_id=%s", run.portfolio.slug, run.id)
        await internal_request(
            settings,
            "POST",
            f"/runs/{run.id}/fail",
            {"error": str(exc), "cancelled": True},
        )
    except Exception as exc:
        message = f"{type(exc).__name__}: {exc}"
        logger.error(
            "evaluation_failed portfolio=%s run_id=%s error=%s",
            run.portfolio.slug,
            run.id,
            message,
        )
        try:
            await internal_request(
                settings,
                "POST",
                f"/runs/{run.id}/fail",
                {"error": message[-4000:], "cancelled": False},
            )
        except Exception:
            logger.exception("evaluation_failure_record_failed run_id=%s", run.id)


async def scheduler(
    settings: EvaluatorRuntimeSettings,
    instance_id: str,
    state: WorkerState,
) -> None:
    write_codex_config(settings)
    while True:
        try:
            if not settings.massive_api_key:
                state.status = "configuration_error"
                state.authenticated = False
                state.last_error = "MASSIVE_API_KEY is required."
            else:
                state.harness_version = await codex_version()
                state.authenticated = await codex_is_authenticated()
                if not state.authenticated:
                    state.status = "authentication_required"
                    state.last_error = "Run `codex login --device-auth` in the application terminal."
                else:
                    response = ClaimResponse.model_validate(
                        await internal_request(
                            settings,
                            "POST",
                            "/claim",
                            {
                                "worker_id": instance_id,
                                "harness": "codex",
                                "harness_version": state.harness_version,
                                "limit": 20,
                            },
                        )
                    )
                    state.poll_seconds = response.settings.poll_seconds
                    if not response.settings.enabled:
                        state.status = "paused"
                        state.last_error = None
                    elif response.runs:
                        state.status = "running"
                        state.active_run_count = len(response.runs)
                        state.last_error = None
                        await asyncio.gather(*(evaluate_run(settings, run) for run in response.runs))
                        state.active_run_count = 0
                        state.status = "idle"
                    else:
                        state.status = "idle"
                        state.last_error = None
        except asyncio.CancelledError:
            raise
        except Exception as exc:
            state.status = "error"
            state.last_error = f"{type(exc).__name__}: {exc}"[-4000:]
            logger.exception("evaluator_poll_failed")
        await asyncio.sleep(state.poll_seconds)


async def heartbeat_loop(
    settings: EvaluatorRuntimeSettings,
    instance_id: str,
    state: WorkerState,
) -> None:
    while True:
        try:
            await internal_request(
                settings,
                "POST",
                "/heartbeat",
                {
                    "instance_id": instance_id,
                    "harness": "codex",
                    "status": state.status,
                    "harness_version": state.harness_version,
                    "authenticated": state.authenticated,
                    "active_run_count": state.active_run_count,
                    "last_error": state.last_error,
                },
            )
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("evaluator_heartbeat_failed")
        await asyncio.sleep(min(state.poll_seconds, 60))


def worker_state_payload(state: WorkerState) -> dict[str, Any]:
    """Return a stable snapshot for focused unit tests."""
    return {
        "status": state.status,
        "harness_version": state.harness_version,
        "authenticated": state.authenticated,
        "active_run_count": state.active_run_count,
        "last_error": state.last_error,
        "poll_seconds": state.poll_seconds,
    }
