"""NYSE-aware scheduler and ChatGPT-authenticated Codex execution worker."""

import asyncio
import json
import logging
import os
import shutil
import tempfile
from datetime import UTC, date, datetime, timedelta
from pathlib import Path
from typing import Any

import httpx
from mcp import ClientSession
from mcp.client.streamable_http import streamable_http_client
from pydantic import BaseModel, Field

from ..services.trading_calendar import NY, close_at, is_trading_day
from .config import EvaluatorSettings, PortfolioJob

logger = logging.getLogger(__name__)

START_BEFORE_CLOSE = timedelta(minutes=90)
CUTOFF_BEFORE_CLOSE = timedelta(minutes=10)


class ProposalPosition(BaseModel):
    symbol: str = Field(min_length=1, max_length=32)
    weight_pct: float = Field(gt=0, le=100)
    note: str = Field(max_length=2000)


class Proposal(BaseModel):
    positions: list[ProposalPosition] = Field(min_length=1)
    note: str = Field(max_length=4000)
    report: str = Field(max_length=20_000)


def evaluation_window(day: date) -> tuple[datetime, datetime]:
    close = close_at(day)
    return close - START_BEFORE_CLOSE, close - CUTOFF_BEFORE_CLOSE


def _toml_string(value: str) -> str:
    return json.dumps(value)


def write_codex_config(settings: EvaluatorSettings) -> None:
    settings.codex_home.mkdir(parents=True, exist_ok=True)
    config = f"""\
# Generated by Portfolio Arena's evaluator worker. Authentication files in this
# directory are preserved; only this dedicated worker configuration is replaced.
web_search = "live"
approval_policy = "never"
default_permissions = ":read-only"
model_reasoning_effort = "xhigh"
service_tier = {_toml_string(settings.service_tier)}

[mcp_servers.portfolio_arena]
url = {_toml_string(settings.arena_mcp_url)}
bearer_token_env_var = "ARENA_MCP_API_KEY"
enabled_tools = ["get_portfolio", "get_effective_date", "validate_symbol", "search_symbols"]
required = true

[mcp_servers.massive]
command = "mcp_massive"
required = true
"""
    (settings.codex_home / "config.toml").write_text(config)


async def codex_version() -> str:
    executable = shutil.which("codex")
    if executable is None:
        raise RuntimeError("codex executable is not installed")
    process = await asyncio.create_subprocess_exec(
        executable,
        "--version",
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await process.communicate()
    if process.returncode != 0:
        raise RuntimeError((stderr or stdout).decode(errors="replace").strip())
    return stdout.decode().strip()


async def codex_is_authenticated() -> bool:
    executable = shutil.which("codex")
    if executable is None:
        return False
    process = await asyncio.create_subprocess_exec(
        executable,
        "login",
        "status",
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL,
    )
    return await process.wait() == 0


def _tool_payload(result: Any) -> dict:
    if result.isError:
        message = " ".join(getattr(item, "text", "") for item in result.content).strip()
        raise RuntimeError(message or "Arena MCP tool returned an error")
    if result.structuredContent is not None:
        payload = result.structuredContent
        if isinstance(payload, dict) and set(payload) == {"result"}:
            payload = payload["result"]
        if isinstance(payload, dict):
            return payload
    for item in result.content:
        text = getattr(item, "text", None)
        if text:
            payload = json.loads(text)
            if isinstance(payload, dict):
                return payload
    raise RuntimeError("Arena MCP tool returned no structured object")


async def call_arena_tool(settings: EvaluatorSettings, name: str, arguments: dict) -> dict:
    timeout = httpx.Timeout(30, read=60)
    async with httpx.AsyncClient(
        headers={"Authorization": f"Bearer {settings.arena_mcp_api_key}"},
        timeout=timeout,
    ) as http_client:
        async with streamable_http_client(
            settings.arena_mcp_url,
            http_client=http_client,
        ) as (read_stream, write_stream, _):
            async with ClientSession(read_stream, write_stream) as session:
                await session.initialize()
                result = await session.call_tool(name, arguments)
                return _tool_payload(result)


def evaluator_prompt(job: PortfolioJob) -> str:
    return f"""\
Evaluate the existing Portfolio Arena portfolio `{job.slug}` for today's scheduled rebalance.

Call the Portfolio Arena `get_portfolio` tool first and treat the returned strategy, allocation
policy, holdings, notes, history, performance, and effective date as authoritative. Research all
decision-relevant current information with Massive and live web search. Every current holding must
re-earn its place, but continuity is useful when the thesis still holds.

Produce a proposal that obeys the returned allocation policy exactly. Use only USD-denominated
equities and ETFs accepted by Portfolio Arena. Do not use cash, mutual funds, options, futures,
indices, FX, shorts, or leverage. Validate unfamiliar symbols. Do not call any write tool: the
worker will validate and submit your final structured proposal atomically.

The report should briefly explain the portfolio-level decision, key evidence, material risks, and
what would change the next evaluation. Position notes should be concise handoff context.
"""


async def run_codex(settings: EvaluatorSettings, job: PortfolioJob) -> Proposal:
    schema_path = Path(__file__).with_name("proposal.schema.json")
    environment = os.environ.copy()
    environment["CODEX_HOME"] = str(settings.codex_home)
    environment["ARENA_MCP_API_KEY"] = settings.arena_mcp_api_key
    environment["MASSIVE_API_KEY"] = settings.massive_api_key
    environment.pop("OPENAI_API_KEY", None)
    environment.pop("CODEX_API_KEY", None)

    with tempfile.TemporaryDirectory(prefix="arena-evaluation-") as temp_dir:
        output_path = Path(temp_dir) / "proposal.json"
        process = await asyncio.create_subprocess_exec(
            "codex",
            "exec",
            "--strict-config",
            "--ephemeral",
            "--skip-git-repo-check",
            "--ignore-rules",
            "--sandbox",
            "read-only",
            "--model",
            job.model,
            "--cd",
            temp_dir,
            "--output-schema",
            str(schema_path),
            "--output-last-message",
            str(output_path),
            "--color",
            "never",
            "-",
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=environment,
        )
        try:
            async with asyncio.timeout(settings.attempt_timeout_seconds):
                stdout, stderr = await process.communicate(evaluator_prompt(job).encode())
        except TimeoutError:
            process.kill()
            await process.wait()
            raise RuntimeError(
                f"Codex attempt exceeded {settings.attempt_timeout_seconds} seconds"
            ) from None
        if process.returncode != 0:
            detail = (stderr or stdout).decode(errors="replace").strip()
            raise RuntimeError(detail[-4000:] or f"Codex exited with {process.returncode}")
        if not output_path.exists():
            raise RuntimeError("Codex completed without writing a proposal")
        return Proposal.model_validate_json(output_path.read_text())


async def evaluate_once(
    settings: EvaluatorSettings,
    job: PortfolioJob,
    scheduled_for: date,
    version: str,
    semaphore: asyncio.Semaphore,
) -> str:
    async with semaphore:
        run_id: int | None = None
        try:
            begin = await call_arena_tool(
                settings,
                "begin_evaluation_run",
                {
                    "portfolio_slug": job.slug,
                    "scheduled_for": scheduled_for.isoformat(),
                    "model": job.model,
                    "codex_version": version,
                },
            )
            action = begin["action"]
            if action != "run":
                logger.info("evaluation_not_started portfolio=%s action=%s", job.slug, action)
                return action
            run_id = int(begin["run"]["id"])
            proposal = await run_codex(settings, job)
            await call_arena_tool(
                settings,
                "submit_evaluation_allocation",
                {
                    "run_id": run_id,
                    "positions": [position.model_dump() for position in proposal.positions],
                    "note": proposal.note,
                    "report": proposal.report,
                },
            )
            logger.info("evaluation_succeeded portfolio=%s run_id=%s", job.slug, run_id)
            return "succeeded"
        except Exception as exc:
            message = f"{type(exc).__name__}: {exc}"
            logger.error(
                "evaluation_failed portfolio=%s run_id=%s error=%s",
                job.slug,
                run_id,
                message,
            )
            if run_id is not None:
                try:
                    await call_arena_tool(
                        settings,
                        "fail_evaluation_run",
                        {"run_id": run_id, "error": message[-4000:]},
                    )
                except Exception:
                    logger.exception("evaluation_failure_record_failed run_id=%s", run_id)
            return "failed"


async def run_session(settings: EvaluatorSettings, scheduled_for: date) -> None:
    version = await codex_version()
    semaphore = asyncio.Semaphore(settings.max_concurrency)
    first_results = await asyncio.gather(
        *(evaluate_once(settings, job, scheduled_for, version, semaphore) for job in settings.jobs)
    )
    retry_jobs = [job for job, result in zip(settings.jobs, first_results, strict=True) if result == "failed"]
    if not retry_jobs:
        return
    _, deadline = evaluation_window(scheduled_for)
    if datetime.now(UTC) >= deadline:
        logger.warning("evaluation_retries_skipped_after_cutoff date=%s", scheduled_for)
        return
    await asyncio.gather(
        *(evaluate_once(settings, job, scheduled_for, version, semaphore) for job in retry_jobs)
    )


def touch_heartbeat(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.touch()


async def heartbeat(settings: EvaluatorSettings) -> None:
    """Keep container health fresh while long Codex attempts are running."""
    while True:
        touch_heartbeat(settings.heartbeat_file)
        await asyncio.sleep(min(settings.poll_seconds, 60))


async def scheduler(settings: EvaluatorSettings) -> None:
    write_codex_config(settings)
    completed_dates: set[date] = set()
    warned_unauthenticated = False
    while True:
        now = datetime.now(UTC)
        today = now.astimezone(NY).date()
        if is_trading_day(today) and today not in completed_dates:
            starts_at, deadline_at = evaluation_window(today)
            if starts_at <= now < deadline_at:
                if await codex_is_authenticated():
                    warned_unauthenticated = False
                    logger.info("evaluation_session_started date=%s", today)
                    await run_session(settings, today)
                    completed_dates.add(today)
                    logger.info("evaluation_session_finished date=%s", today)
                elif not warned_unauthenticated:
                    logger.error(
                        "Codex is not logged in. Run `codex login --device-auth` in the worker "
                        "container; the scheduler will keep waiting without consuming attempts."
                    )
                    warned_unauthenticated = True
        completed_dates = {day for day in completed_dates if day >= today - timedelta(days=2)}
        await asyncio.sleep(settings.poll_seconds)
