"""Record independent revision history for shared Settings prompts.

Revision ID: 0030
Revises: 0029
"""

import sqlalchemy as sa

from alembic import op

revision = "0030"
down_revision = "0029"
branch_labels = None
depends_on = None

# Freeze defaults so upgrades do not depend on future application changes.
DEFAULTS = {
    "allocation_policy_instructions": "Use 0–{{derived_max_positions}} selections, each weighted\n"
    "{{min_position_weight_pct}}–{{max_position_weight_pct}}% of "
    "NAV.\n"
    "For n selections, weights must total min(100, n × maximum "
    "position weight), to four decimals.\n"
    "The server puts the remainder in direction-matched SPY, "
    "outside these limits; do not submit it.\n"
    "Use only USD-denominated equities and ETFs, and validate every "
    "selected symbol.",
    "automated_submission_instructions": "Do not call any write tool; return the structured response "
    "for the worker to submit.\n"
    "\n"
    "- `proposal`: selected securities, including partial "
    "allocations.\n"
    "- `abstained`: completed research found no qualifying "
    "securities; no positions.\n"
    "Both are successful outcomes: use an empty `error` and null "
    "`blocked_reason`.\n"
    "- `blocked`: required portfolio context or research was "
    "unavailable. Return no positions, explain\n"
    "  the error, and set `blocked_reason` to "
    "`portfolio_unavailable` or `research_unavailable`.\n"
    "\n"
    "In `report`, explain the decision, evidence, material "
    "risks, and what would change your assessment.\n"
    "Partial allocations and abstentions require both `note` and "
    "`report`: explain the research coverage\n"
    "and why the strongest excluded candidates failed.\n"
    "Preserve any completed research if blocked. Keep position "
    "notes concise.\n",
    "long_direction_instructions": "This is an all-long portfolio. Submit positive weights for "
    "securities expected to outperform SPY.",
    "managed_manual_submission_instructions": "When the analysis is complete, call "
    "`create_allocation` exactly once with the portfolio id "
    "returned by\n"
    "`get_portfolio`. Include a concise portfolio-level "
    "note and useful per-position notes so the next\n"
    "evaluation can understand the decision. For a partial "
    "allocation or abstention, explain the research\n"
    "coverage and why the strongest excluded candidates "
    "failed in the portfolio-level note.",
    "managed_wrapper_prompt": "Evaluate the Portfolio Arena portfolio `{{portfolio_slug}}` and "
    "produce its next allocation.\n"
    "\n"
    "Call `get_portfolio` first. Use its strategy, direction, allocation "
    "policy, effective boundary, holdings,\n"
    "notes, history, and performance as authoritative context.\n"
    "\n"
    "Select securities with a specific, falsifiable financial thesis and a "
    "supported prospective advantage\n"
    "over the direction-matched SPY reference at current prices. Compare "
    "plausible outcomes, their likelihood,\n"
    "and adverse risks; test the strongest opposing interpretation. Use "
    "ranges where precision is unsupported.\n"
    "\n"
    "The strategy's mechanism and explicit requirements are essential. "
    "Indicator lists guide relevant\n"
    "research, not universal checklists. Assess forecasts and market "
    "beliefs probabilistically. Publicity,\n"
    "information age, or a prior price move alone proves neither "
    "opportunity nor disqualification.\n"
    "State a plausible thesis horizon; an execution boundary alone sets no "
    "holding deadline.\n"
    "\n"
    "Search broadly across the eligible US market with Massive and live web "
    "research. Support decisive facts\n"
    "with primary evidence where available; label inferences and material "
    "gaps. Cite sources and timestamp\n"
    "prices, allowing for movement before entry. Never assume future "
    "information or execution prices.\n"
    "\n"
    "Rank and weight qualifying candidates by expected excess return, "
    "conviction, and risk within the sizing\n"
    "limits. Do not target a position count or abstention rate, add filler, "
    "or substitute SPY for research.\n"
    "Submit the supported selections; abstain only when completed broad "
    "research supports none. Uncertainty\n"
    "alone is not disqualifying, but missing evidence essential to a thesis "
    "is.\n"
    "\n"
    "If history is empty, build the initial allocation. Otherwise reassess "
    "existing holdings and alternatives\n"
    "using current evidence and prices. A supported holding needs no new "
    "headline. Retain, resize, or replace\n"
    "it according to prospective return, thesis changes, valuation, and "
    "risk. Avoid automatic retention,\n"
    "turnover targets, and trading on ordinary price noise.\n"
    "\n"
    "Direction:\n"
    "{{direction_instructions}}\n"
    "\n"
    "Strategy:\n"
    "{{strategy_text}}\n"
    "\n"
    "Allocation policy:\n"
    "{{allocation_policy}}\n"
    "\n"
    "This decision replaces previous holdings; abstaining moves them into "
    "the reference.\n"
    "\n"
    "{{submission_instructions}}",
    "rebuilt_manual_submission_instructions": "When the analysis is complete, call `create_signal` "
    "exactly once with the portfolio id returned by\n"
    "`get_portfolio`. Include a concise portfolio-level "
    "note and useful per-position notes that explain\n"
    "the independent signal. For a partial allocation or "
    "abstention, explain the research coverage and\n"
    "why the strongest excluded candidates failed in the "
    "portfolio-level note.",
    "rebuilt_wrapper_prompt": "Evaluate the Portfolio Arena portfolio `{{portfolio_slug}}` and "
    "produce its next independent signal\n"
    "allocation.\n"
    "\n"
    "Call `get_portfolio` first. Use its strategy, direction, allocation "
    "policy, and effective boundary\n"
    "as authoritative context. Do not use prior portfolio state from any "
    "source.\n"
    "\n"
    "Select securities with a specific, falsifiable financial thesis and a "
    "supported prospective advantage\n"
    "over the direction-matched SPY reference at current prices. Compare "
    "plausible outcomes, their likelihood,\n"
    "and adverse risks; test the strongest opposing interpretation. Use "
    "ranges where precision is unsupported.\n"
    "\n"
    "The strategy's mechanism and explicit requirements are essential. "
    "Indicator lists guide relevant\n"
    "research, not universal checklists. Assess forecasts and market "
    "beliefs probabilistically. Publicity,\n"
    "information age, or a prior price move alone proves neither "
    "opportunity nor disqualification.\n"
    "State a plausible thesis horizon; an execution boundary alone sets no "
    "holding deadline.\n"
    "\n"
    "Search broadly across the eligible US market with Massive and live web "
    "research. Support decisive facts\n"
    "with primary evidence where available; label inferences and material "
    "gaps. Cite sources and timestamp\n"
    "prices, allowing for movement before entry. Never assume future "
    "information or execution prices.\n"
    "\n"
    "Rank and weight qualifying candidates by expected excess return, "
    "conviction, and risk within the sizing\n"
    "limits. Do not target a position count or abstention rate, add filler, "
    "or substitute SPY for research.\n"
    "Submit the supported selections; abstain only when completed broad "
    "research supports none. Uncertainty\n"
    "alone is not disqualifying, but missing evidence essential to a thesis "
    "is.\n"
    "\n"
    "Build the complete signal from scratch, independently of previous "
    "signals.\n"
    "Subject to the allocation policy, a single security may receive 100% "
    "when it is the only\n"
    "qualifying opportunity.\n"
    "\n"
    "Direction:\n"
    "{{direction_instructions}}\n"
    "\n"
    "Strategy:\n"
    "{{strategy_text}}\n"
    "\n"
    "Allocation policy:\n"
    "{{allocation_policy}}\n"
    "\n"
    "{{submission_instructions}}",
    "short_direction_instructions": "This is an all-short portfolio. Select securities whose prices "
    "are expected to underperform SPY\n"
    "so the short book can outperform the Short SPY reference. Submit "
    "positive weights; the server\n"
    "interprets them as short exposure.",
}


# Recovered from 865251e68e4b51f5e2b6754415c3ab6576179c72.
# Numeric interpolation becomes template placeholders.
BASELINE = {
    "allocation_policy_instructions": "Select only qualifying securities; do not add marginal or omit "
    "qualifying selections.\n"
    "Use 0–{{derived_max_positions}} selections, each weighted "
    "{{min_position_weight_pct}}–{{max_position_weight_pct}}% of "
    "NAV.\n"
    "For n selections, weights must total min(100, n × maximum "
    "position weight), to four decimals.\n"
    "The server puts the remainder in direction-matched SPY, "
    "outside these limits; do not submit it.\n"
    "If completed research finds nothing qualifying, abstain with "
    "no positions.\n"
    "Explain any partial allocation or abstention in the decision "
    "note.\n"
    "Use only USD-denominated equities and ETFs, and validate every "
    "selected symbol.",
    "automated_submission_instructions": "Do not call any write tool; return the structured response "
    "for the worker to submit.\n"
    "\n"
    "- `proposal`: selected securities, including partial "
    "allocations.\n"
    "- `abstained`: completed research found no qualifying "
    "securities; no positions.\n"
    "Both are successful outcomes: use an empty `error` and null "
    "`blocked_reason`.\n"
    "- `blocked`: required portfolio context or research was "
    "unavailable. Return no positions, explain\n"
    "  the error, and set `blocked_reason` to "
    "`portfolio_unavailable` or `research_unavailable`.\n"
    "\n"
    "In `report`, explain the decision, evidence, material "
    "risks, and what would change your assessment.\n"
    "For partial allocations or abstentions, describe the "
    "research and why no more securities qualified.\n"
    "Preserve any completed research if blocked. Keep position "
    "notes concise.\n",
    "long_direction_instructions": "This is an all-long portfolio. Submit positive weights for "
    "securities expected to outperform SPY.",
    "managed_manual_submission_instructions": "When the analysis is complete, call "
    "`create_allocation` exactly once with the portfolio id "
    "returned by\n"
    "`get_portfolio`. Include a concise portfolio-level "
    "note and useful per-position notes so the next\n"
    "evaluation can understand the decision.",
    "managed_wrapper_prompt": "Evaluate the Portfolio Arena portfolio `{{portfolio_slug}}` and "
    "produce its next allocation.\n"
    "\n"
    "Call the Portfolio Arena `get_portfolio` tool first. Treat the "
    "returned prompt mode, strategy,\n"
    "allocation policy, current holdings, notes, allocation history, "
    "performance, and effective date as\n"
    "authoritative. Follow the eligibility rules and submission "
    "instructions in this execution prompt.\n"
    "\n"
    "Act as a US equity portfolio manager aiming to outperform the "
    "portfolio's direction-matched SPY\n"
    "reference. Search across the full eligible US market rather than "
    "defaulting to index constituents,\n"
    "household names, or recent winners. Do not select SPY as a substitute "
    "for research. Select a stock\n"
    "or ETF only when it has a distinct, falsifiable, security-specific "
    "thesis supported by current evidence.\n"
    "\n"
    "If the returned allocation history is empty, construct the portfolio's "
    "initial allocation. Otherwise,\n"
    "manage and rebalance the existing portfolio rather than rebuilding it "
    "without reference to its\n"
    "history.\n"
    "\n"
    "Reassess every holding and credible candidate using current evidence "
    "and current prices. Every\n"
    "holding must re-earn its place. Use the portfolio history and notes to "
    "update each thesis, but do not\n"
    "give an existing position an automatic retention advantage. Do not "
    "target either low or high\n"
    "turnover. Change holdings or target weights when the current evidence "
    "indicates that another\n"
    "allocation should materially improve strategy-aligned prospective "
    "excess return.\n"
    "Do not trade solely because of ordinary price noise,\n"
    "repeated information, or small or\n"
    "unstable ranking differences.\n"
    "\n"
    "Direction instructions:\n"
    "{{direction_instructions}}\n"
    "\n"
    "Strategy:\n"
    "{{strategy_text}}\n"
    "\n"
    "Allocation policy:\n"
    "{{allocation_policy}}\n"
    "\n"
    "This decision replaces previous holdings; abstaining moves them into "
    "the reference.\n"
    "\n"
    "Research all decision-relevant current information with Massive and "
    "live web search.\n"
    "\n"
    "{{submission_instructions}}",
    "rebuilt_manual_submission_instructions": "When the analysis is complete, call `create_signal` "
    "exactly once with the portfolio id returned by\n"
    "`get_portfolio`. Include a concise portfolio-level "
    "note and useful per-position notes that explain\n"
    "the independent signal.",
    "rebuilt_wrapper_prompt": "Evaluate the Portfolio Arena portfolio `{{portfolio_slug}}` and "
    "produce its next independent signal\n"
    "allocation.\n"
    "\n"
    "Call the Portfolio Arena `get_portfolio` tool first. Treat the "
    "returned prompt mode, strategy,\n"
    "allocation policy, and effective date as authoritative. Follow the "
    "eligibility rules and submission\n"
    "instructions in this execution prompt.\n"
    "\n"
    "Do not use prior portfolio state from any source when constructing or "
    "weighting the signal.\n"
    "\n"
    "Act as a US equity security selector aiming to outperform the "
    "portfolio's direction-matched SPY\n"
    "reference. Search across the full eligible US market rather than "
    "defaulting to index constituents,\n"
    "household names, or recent winners. Do not select SPY as a substitute "
    "for research.\n"
    "\n"
    "This is an independent security-selection signal. Breadth must be an "
    "outcome of the evidence, not a\n"
    "diversification target. Select only securities that independently "
    "qualify under the strategy. Never\n"
    "add a marginal security merely to increase the position count or make "
    "the allocation appear more\n"
    "diversified.\n"
    "\n"
    "Weight qualifying securities comparatively using expected excess "
    "return, conviction, evidence\n"
    "quality, downside, and the strength and timing of the recognition "
    "mechanism. Stronger opportunities\n"
    "should receive higher weights. Subject to the allocation policy, a "
    "single security may receive 100%\n"
    "when it is the only opportunity that genuinely qualifies, but "
    "concentration must reflect the evidence\n"
    "rather than convenience or familiarity.\n"
    "\n"
    "At every evaluation, construct the complete signal independently from "
    "scratch. Search broadly and\n"
    "evaluate candidates without regard to previous signals.\n"
    "\n"
    "Direction instructions:\n"
    "{{direction_instructions}}\n"
    "\n"
    "Strategy:\n"
    "{{strategy_text}}\n"
    "\n"
    "Allocation policy:\n"
    "{{allocation_policy}}\n"
    "\n"
    "Research all decision-relevant current information with Massive and "
    "live web search.\n"
    "\n"
    "{{submission_instructions}}",
    "short_direction_instructions": "This is an all-short portfolio. Select securities whose prices "
    "are expected to underperform SPY\n"
    "so the short book can outperform the Short SPY reference. Submit "
    "positive weights; the server\n"
    "interprets them as short exposure.",
}


def upgrade() -> None:
    op.create_table(
        "setting_prompt_versions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("key", sa.Text(), sa.ForeignKey("settings.key", ondelete="CASCADE"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("restored_from_version", sa.Integer(), nullable=True),
        sa.CheckConstraint("version >= 1", name="setting_prompt_versions_version_check"),
        sa.UniqueConstraint("key", "version", name="setting_prompt_versions_key_version_key"),
        sa.ForeignKeyConstraint(
            ["key", "restored_from_version"],
            ["setting_prompt_versions.key", "setting_prompt_versions.version"],
            name="setting_prompt_versions_restore_fkey",
        ),
    )
    connection = op.get_bind()
    for key, value in sorted(DEFAULTS.items()):
        connection.execute(
            sa.text("INSERT INTO settings (key, value) VALUES (:key, :value) ON CONFLICT (key) DO NOTHING"),
            {"key": key, "value": value},
        )
        connection.execute(
            sa.text("INSERT INTO setting_prompt_versions (key, version, text) VALUES (:key, 1, :text)"),
            {"key": key, "text": BASELINE[key]},
        )
        connection.execute(
            sa.text(
                "INSERT INTO setting_prompt_versions (key, version, text) "
                "SELECT key, 2, value FROM settings WHERE key = :key"
            ),
            {"key": key},
        )


def downgrade() -> None:
    # Active values already live in settings; preserve them when removing history.
    op.drop_table("setting_prompt_versions")
